### ISSUE TITLE
Tabs adds itself 10 Times instead of 1 time

### ISSUE THREAD

**Issue by benny-96** [vsDizzy/SaveAsMHT#10]
Tabs adds itself 10 Times instead of 1 time while adding a Tab to an already saved and currently open session. Once closed and reopened the saved session, 100 Tabs are retrieved for 10 Tabs, opening leading to Chrome crash with extremely high CPU usage. How one can backup saved prior to reinstall in an attempt to fix the issue. Thanks.

**Comment by vsDizzy** [comment]
I'm not sure this is SaveAsMHT related as It does nothing with tabs or sessions. But if you assist on the issue please give me the steps to reproduce the problem.

**Comment by vsDizzy** [comment]
Seems like this is not plugin related.
