### ISSUE TITLE
Port to Firefox

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [vsDizzy/SaveAsMHT#11]
Since Firefox Quantum released, there is no extension can do this, however it’s possible to create one via porting your extension to Firefox. Some related documentations can be found at MDN Web Docs.

**Comment by vsDizzy** [comment]
Firefox has no 1:1 API support, so currently no porting possible. https://github.com/vsDizzy/SaveAsMHT/issues/6

**Comment by KrasnayaPloshchad** [comment]
Oh I understand. It’s not possible to do it via native call from Firefox, unless you port UnMHT to Firefox.
