### ISSUE TITLE
Save as MHT is offering only Save as TXT file (?!)

### ISSUE THREAD

**Issue by Ellery-D** [vsDizzy/SaveAsMHT#15]
I added Save as MHT to a Chrome on a brand new laptop (HP Spectre x360 (2019).
Yet, it only has an option to Save as TXT. The folder browser SAVE AS dialog does not allow me to change the file type to MHT.

I tried removing/adding Save as MHT and I have even RE-installed Chrome. Even more puzzling, I tried it on another new PC (HP Pavilion) with the same results. Is the problem on your end, or do I have an incompatible security setting -- or something wrong with my Norton or MalwareBytes apps?

For now, I have resorted to opening Internet Explorer which has this feature built-in. But that browser is no longer supported by Microsoft. They have replaced it with Edge.

Ellery-D

**Comment by vsDizzy** [comment]
Tested with latest Chrome (75.0.3770.100), all is fine on my end.
In theory you can save is as `.txt` and then rename saved file in Windows Explorer (Win+E)

**Comment by Ellery-D** [comment]
That's fascinating!... I had wrongly assumed that saving as "TXT" would generate a TXT only file (without HTML or any styles applied). But, you are correct. It only says TXT and adds that extension. It is actually saving as an MHT file...

I can live with this -- but just so that you are aware: I have now confirmed the problem on three new PCs. Two are HP and one is Dell. Only my original (older) Asus laptop shows the option to save as MHT.

I am responsible for setting up these new PCs. My guess is that something in my antivirus or other configuration choices is interfering with the Save As (FILETYPE) drop down options.

Ellery-D

**Comment by brz1980** [comment]
I'm using the latest version of Chrome and am having the exact same issue - it only lets me save as .txt, and while renaming it manually to .mht does work, it's kind of annoying. Just wanted to share as a fix would be great if possible.

**Comment by brz1980** [comment]
I get the same issue no matter which site I try it on. I just tried it on yahoo's main page and this is what comes up in the save as dialog. What's weird is it used to work fine. I tried disabling Kaspersky anti-virus but no change. Also sending screenshot of the extension options.  I really appreciate the effort to fix it. 


 





 

    On Wednesday, October 16, 2019, 10:53:47 AM EDT, vsDizzy <notifications@github.com> wrote:  
 
 
I'm trying to reproduce this on my end. Is it broken for specific url or completely?
Can you share the url you're trying to save?

**Comment by Ellery-D** [comment]
I apologize for not updating this thread with a good resolution:

The author contacted me. Although he seemed puzzled that the only SAVE AS extension had switched to TXT (rather than MHT). He told me to simply save the file and then rename .TXT to .MHT. This works! The file is in proper mht form. For some reason, the browser presents the SAVE AS option as TXT.

Simple solution: Just rename it, so that is associates with your favorite MHT app or browser.

~Ellery

**Comment by cyberdriveblr** [comment]
Tested with latest Chrome (78.0.3904.70),
and I am having the exact same issue:
only has an option to Save as TXT.

**Comment by Ellery-D** [comment]
A minor bug is causing the SAVE AS dialog to put a .TXT onto the saved file.
It is actually an MHT file. Simply rename the ending from txt to mht.

~Ellery

_____________

At 16:29 2019.10.26, cyberdriveblr wrote:

>Tested with latest Chrome (78.0.3904.70),
>and I am having the exact same issue:
>only has an option to Save as TXT.

**Comment by cyberdriveblr** [comment]
> It is actually an MHT file. 

Yes, but this minor bug is still not resolved.
For some reason, the browser presents the SAVE AS option as TXT.

**Comment by vsDizzy** [comment]
Should be fixed by now.
