### ISSUE TITLE
SaveAsMHT doesn't work on one webpage

### ISSUE THREAD

**Issue by GeekUser2** [vsDizzy/SaveAsMHT#17]
SaveAsMHT doesn't work on https://www.geographya.tk/2019/07/90-mil-mapas-antigos-em-alta-resolucao.html

**Comment by vsDizzy** [comment]
Thanks. It is something wrong in the filename `90 mil mapas antigos em alta resolução para download ~ Geographya.mht` maybe ~ character. Will fix in the next version.

**Comment by GeekUser2** [comment]
Thank you very much.
Is it possible to add a feature that exist(ed) on Firefox add-on 'Mozilla
Archive Format'?:
When a file  .mht  is(was) opened, then appears a little yellow bar on the
top of the webpage with a link to the original file on the Internet.
This feature is very useful to let the user get the most recent version of
the page, in the case he needs it.
Best Regards

vsDizzy <notifications@github.com> escreveu no dia sábado, 17/08/2019 à(s)
21:24:

**Comment by vsDizzy** [comment]
'~' fixed in 0.1.2
info is already added

**Comment by GeekUser2** [comment]
Thank you very much.

Best regards

vsDizzy <notifications@github.com> escreveu no dia terça, 14/04/2020 à(s)
17:05:
