### ISSUE TITLE
Поддержка кирилицы

### ISSUE THREAD

**Issue by opiums9** [vsDizzy/SaveAsMHT#2]
Здравствуйте уважаемый разработчик, хотелось бы поддержку кирилицы некоторых параметров файла .mht:
`From: <Saved by Blink>
Subject: 15???????-????????? ????????????? ???????
Date: Mon, 26 Mar 2017 04:11:50 -0000
MIME-Version: 1.0
Content-Type: multipart/related;
	type="text/html";
	boundary="----=_NextPart_000_0334_1AB6F501.E6BB589A"`

`Original Subject: 15 онлайн-библиотек с бесплатными книгами`

А так же хотелось бы изменить расширение с заглавных букв **.MHT** на строчные **.mht**.
Заранее спасибо.

**Comment by vsDizzy** [comment]
К сожалению .mht файл формируется движком хрома. Тут разве что добавить постобработку, которая заменяла бы поля, как бы не поломать чего.
Строчные .mht блокируются движком, из-за паранои разработчиков с безопасностью.

**Comment by vsDizzy** [comment]
Сделал в версии 0.0.5 экспериментальную поддержку для Subject. Включается галочкой в настройках.

**Comment by vsDizzy** [comment]
Теперь по умолчанию галочка включена.
