### ISSUE TITLE
BUG: Save to TXT instead of MHT

### ISSUE THREAD

**Issue by michelleagn** [vsDizzy/SaveAsMHT#20]
Worked well just before - saved to MHT, but now saves to TXT instead of MHT.
If I manually change filename from TXT to MHT a get right result, but I need to change name manually each time I use extension.

**Comment by lance8765** [comment]
Same issue here.

**Comment by aqlance** [comment]
When I load the extensions via "Load Unpacked", and try to debug, I get 2 errors. Please see the attached screenshots.
![Debug1](https://user-images.githubusercontent.com/25678596/67629120-bca21600-f897-11e9-9fec-0fc48f0d10cf.JPG)
![Debug2](https://user-images.githubusercontent.com/25678596/67629121-be6bd980-f897-11e9-9f15-3243713b6a25.JPG)

**Comment by aqlance** [comment]
To rule out the possibility of any bug in this extension, I loaded another Save as MHT extension from the store. It also ended up saving the file as .TXT!! Looks like it's an issue with the latest version of Chrome/API used by extensions, which got updated recently.

**Comment by vsDizzy** [comment]
Should be fixed by now in 0.1.1
