### ISSUE TITLE
executable version, would it be possible?

### ISSUE THREAD

**Issue by 00BbnN00** [vsDizzy/SaveAsMHT#23]
would it be possible to have a version in executable format (eg "SaveAsMht.exe") commandable from the command line? 
sending commands like <url>, <destination / folder>, <name.mht>?
[1 page for time , no need multi table ]
or a small executable that takes these inputs, you pass them to the app to get the saved file?

es  : 
cmd / "SaveAsMht.exe"  + <url>, <destination / folder>, <name.mht>, / enter 
case A)  the programm do the work 
case B) ----->  input go to app "SaveAsMht" in chrome and the app do the work.

result : in the <destination / folder> we have the <name.mht> of the <url>

**Comment by vsDizzy** [comment]
I understand the problem. But I have no idea how this could be implemented. Sorry.
