### ISSUE TITLE
Extension must be updated to Manifest V3 before January 2023! (will stop working then)

### ISSUE THREAD

**Issue by DarrenSem** [vsDizzy/SaveAsMHT#27]
This awesome extension must be updated to "Manifest V3" before January 2023 **(the current version will stop working after that!)**

[January 2023: The Chrome browser will no longer run Manifest V2 extensions.](https://developer.chrome.com/blog/mv2-transition/)

[Chrome stops running Manifest V2 extensions](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/)

I use this pretty much daily, really hoping @vsDizzy is able to respond in time... thanks!

**Comment by vsDizzy** [comment]
manifest is updated to v3
