### ISSUE TITLE
Configurable hotkey

### ISSUE THREAD

**Issue by RadekSoltys** [vsDizzy/SaveAsMHT#5]
Thanks for this essential extension! - It spared me running Firefox in parallel just to be able to save web articles.
Could we have the option to re-assign or disable the default hotkey [Alt+S], please? - it conflicts e.g. with the online Outlook, which I'm using a lot...

**Comment by vsDizzy** [comment]
1. Right click on extension icon, choose 'manage extensions'.
2. Scroll down to very bottom, and see at the bottom right 'Keyboard shortcuts'
3. Assign keys that you want.
