### ISSUE TITLE
Currently working with Firefox, official support planned?

### ISSUE THREAD

**Issue by kekkc** [vsDizzy/SaveAsMHT#6]
Hi,

great WebExtension ;) With "Chrome Store Foxified", the extension is directly working with Firefox, too. Are there any plans to submit this to Firefox AMO, too?

Guess the required customization would be minimal, or can be directly copied from the created files of "Chrome Store Foxified". This gets pretty important, because the old MAFF & UNMHT plugins will no longer work with the next firefox version and won't be reprogrammed as WebExtension.

This leaves 200.000 active MHT users without any possibility to display or save MHT files. It would be fantastic if SaveAsMHT could be submitted to AMO, too. There's even a guide for adjusting a chrome extension: 
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension

Greetz

**Comment by vsDizzy** [comment]
Hi. Currently the PageCapture API which I'm using is not implemented in Firefox.

**Comment by mzso** [comment]
[**@vsDizzy**](https://github.com/vsDizzy) commented on [2017. okt. 17. 02:04 CEST](https://github.com/vsDizzy/SaveAsMHT/issues/6#issuecomment-337078482 "2017-10-17T00:04:13Z - Replied by Github Reply Comments"):
> Hi. Currently the PageCapture API which I'm using is not implemented in Firefox.  
> 
> P.S. The funny thing is that Firefox tab could be [saved as PDF](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/saveAsPDF).

But would that even help with viewing mht files or just saving? Chromium has built in support for viewing HTML files,  FF doesn't
