### ISSUE TITLE
Link to the original

### ISSUE THREAD

**Issue by KOT040188** [vsDizzy/SaveAsMHT#7]
Hey. I like this extension. But I lack one function. I need to have a link to the original added at the bottom or at the top of the page.

**Comment by vsDizzy** [comment]
This functionality is already implemented. Make sure you have this checkbox enabled.
![](https://image.prntscr.com/image/7vx1cgs_ThShOKZnWRdwxg.png)

**Comment by KOT040188** [comment]
I'm sorry, I didn't notice. Thank you.

**Comment by KOT040188** [comment]
You probably did not understand me. I need to add a link to the original when saving. Например вверху или внизу страницы.This function is implemented in the extension https://chrome.google.com/webstore/detail/save-page-we/dhhpefjklgkmgeafimnjhojgjamoafof

**Comment by vsDizzy** [comment]
Oh, i see what you're saying. I'm not going to to implement quoted-printable packer in near future. Sorry.
