### ISSUE TITLE
missing context menu with old chrome versions

### ISSUE THREAD

**Issue by TekBear** [vsDizzy/SaveAsMHT#8]
I am using old version of chrome. an entry in the context menu is not seen. developer mode shows these console errors:

    Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode 
    promisify.js:20
    
    Uncaught SyntaxError: Unexpected token function
    background.js:26

I guess you don't support this version - is there a way I can change the code and fix it so it works on Chrome 48.x assuming it is just context menu insertion issue?

**Comment by vsDizzy** [comment]
Just update Chrome, I'm using latest **EsNext** features.
